import { TipoAsistencia } from "@/interfaces/shared/AsistenciaRequests";

export const CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTAR_ASISTENCIA_DE_PERSONAL = 5;
export const CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTAR_ASISTENCIA_DE_ESTUDIANTES_SECUNDARIA = 5;
export const CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTAR_ASISTENCIA_DE_ESTUDIANTES_PRIMARIA = 5;

export const CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTE_ASISTENCIAS: Record<
  TipoAsistencia,
  number
> = {
  [TipoAsistencia.ParaPersonal]:
    CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTAR_ASISTENCIA_DE_PERSONAL,
  [TipoAsistencia.ParaEstudiantesSecundaria]:
    CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTAR_ASISTENCIA_DE_ESTUDIANTES_SECUNDARIA,
  [TipoAsistencia.ParaEstudiantesPrimaria]:
    CANTIDAD_MINUTOS_MAXIMO_PARA_DESCARTAR_ASISTENCIA_DE_ESTUDIANTES_PRIMARIA,
};
