export const INTERVALO_MINUTOS_SINCRONIZACION_HORA_REAL = 12;
export const TIEMPO_PARA_ACTUALIZAR_MINIMO_HORA_AL_VOLVER_A_VER_PAGINA_MS =
  6 * 60 * 1000; // 6 minutos
export const NOMBRE_TIMESTAMP_ULTIMA_CONSULTA_LOCAL_STORAGE =
  "ultimaConsultaHoraReal";
