export type TypeEventAvailable =
  | "click"
  | "mousemove"
  | "mouseout"
  | "mousedown"
  | "mouseup"
  | "mouseenter"
  | "mouseover"
  | "touchstart"
  | "touchmove"
  | "touchend"
  | "change"
  | "input"
  | "keyup"
  | "keydown"
  | "error";
